### ISSUE TITLE
LDAPS Support

### ISSUE THREAD

**Issue by LukeShortCloud** [dfederlein/ansible-tower-demo#3]
As far as I can tell, there is no TLS certificate setup with OpenLDAP on a default installation. For testing secure authentication I would like to have the option to have this available by default. The end-goal is to have both LDAP and LDAPS protocols available for use after the lab is setup.

I'm investigating into this and will submit a PR if I can come to a resolution on this.

**Comment by dfederlein** [comment]
This isn't a testing or lab framework. This is a simple demo. I'm not interested in maintaining lab or testing infra playbooks. If you'd like that feature, please feel free to fork and use however you want.
